---
apiVersion: v1
kind: Secret
metadata:
  name: __NAMESPACE_NAME__-secret
  namespace: __NAMESPACE_NAME__
type: Opaque
stringData:
  JWT_SECRET: __JWT_SECRET__
  DB_PASSWORD: __DB_PASSWORD__
  SENTRY_DSN: __SENTRY_DSN__
  SENTRY_AUTH_TOKEN: __SENTRY_AUTH_TOKEN__
