---
apiVersion: v1
kind: ConfigMap
metadata:
  name: __NAMESPACE_NAME__-config-map
  namespace: __NAMESPACE_NAME__
data:
  DB_NAME: 'acurast_processor_management_backend'
  DB_USER: 'acurast_processor_management_backend'
  DB_HOST: postgres.postgres
  ENVIRONMENT: 'production'
  API_KEY_READ: __API_KEY_READ__
  API_KEY_WRITE: __API_KEY_WRITE__
